# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from blog.protos import blog_pb2 as blog_dot_protos_dot_blog__pb2


class BlogStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetPosts = channel.unary_unary(
                '/blog.Blog/GetPosts',
                request_serializer=blog_dot_protos_dot_blog__pb2.GetPostsRequest.SerializeToString,
                response_deserializer=blog_dot_protos_dot_blog__pb2.GetPostsResponse.FromString,
                )
        self.GetPostBySlug = channel.unary_unary(
                '/blog.Blog/GetPostBySlug',
                request_serializer=blog_dot_protos_dot_blog__pb2.GetPostBySlugRequest.SerializeToString,
                response_deserializer=blog_dot_protos_dot_blog__pb2.GetPostBySlugResponse.FromString,
                )
        self.CreatePost = channel.unary_unary(
                '/blog.Blog/CreatePost',
                request_serializer=blog_dot_protos_dot_blog__pb2.CreatePostRequest.SerializeToString,
                response_deserializer=blog_dot_protos_dot_blog__pb2.CreatePostResponse.FromString,
                )
        self.UpdatePostBySlug = channel.unary_unary(
                '/blog.Blog/UpdatePostBySlug',
                request_serializer=blog_dot_protos_dot_blog__pb2.UpdatePostBySlugRequest.SerializeToString,
                response_deserializer=blog_dot_protos_dot_blog__pb2.UpdatePostBySlugResponse.FromString,
                )
        self.DeletePostBySlug = channel.unary_unary(
                '/blog.Blog/DeletePostBySlug',
                request_serializer=blog_dot_protos_dot_blog__pb2.DeletePostBySlugRequest.SerializeToString,
                response_deserializer=blog_dot_protos_dot_blog__pb2.DeletePostBySlugResponse.FromString,
                )
        self.GetTags = channel.unary_unary(
                '/blog.Blog/GetTags',
                request_serializer=blog_dot_protos_dot_blog__pb2.GetTagsRequest.SerializeToString,
                response_deserializer=blog_dot_protos_dot_blog__pb2.GetTagsResponse.FromString,
                )
        self.GetTagBySlug = channel.unary_unary(
                '/blog.Blog/GetTagBySlug',
                request_serializer=blog_dot_protos_dot_blog__pb2.GetTagBySlugRequest.SerializeToString,
                response_deserializer=blog_dot_protos_dot_blog__pb2.GetTagBySlugResponse.FromString,
                )
        self.GetPostComments = channel.unary_unary(
                '/blog.Blog/GetPostComments',
                request_serializer=blog_dot_protos_dot_blog__pb2.GetPostCommentsRequest.SerializeToString,
                response_deserializer=blog_dot_protos_dot_blog__pb2.GetPostCommentsResponse.FromString,
                )
        self.CreatePostComment = channel.unary_unary(
                '/blog.Blog/CreatePostComment',
                request_serializer=blog_dot_protos_dot_blog__pb2.CreatePostCommentRequest.SerializeToString,
                response_deserializer=blog_dot_protos_dot_blog__pb2.CreatePostCommentResponse.FromString,
                )
        self.UpdatePostComment = channel.unary_unary(
                '/blog.Blog/UpdatePostComment',
                request_serializer=blog_dot_protos_dot_blog__pb2.UpdatePostCommentRequest.SerializeToString,
                response_deserializer=blog_dot_protos_dot_blog__pb2.UpdatePostCommentResponse.FromString,
                )
        self.DeletePostComment = channel.unary_unary(
                '/blog.Blog/DeletePostComment',
                request_serializer=blog_dot_protos_dot_blog__pb2.DeletePostCommentRequest.SerializeToString,
                response_deserializer=blog_dot_protos_dot_blog__pb2.DeletePostCommentResponse.FromString,
                )
        self.GetPostLikes = channel.unary_unary(
                '/blog.Blog/GetPostLikes',
                request_serializer=blog_dot_protos_dot_blog__pb2.GetPostLikesRequest.SerializeToString,
                response_deserializer=blog_dot_protos_dot_blog__pb2.GetPostLikesResponse.FromString,
                )
        self.CreatePostLike = channel.unary_unary(
                '/blog.Blog/CreatePostLike',
                request_serializer=blog_dot_protos_dot_blog__pb2.CreatePostLikeRequest.SerializeToString,
                response_deserializer=blog_dot_protos_dot_blog__pb2.CreatePostLikeResponse.FromString,
                )
        self.DeletePostLike = channel.unary_unary(
                '/blog.Blog/DeletePostLike',
                request_serializer=blog_dot_protos_dot_blog__pb2.DeletePostLikeRequest.SerializeToString,
                response_deserializer=blog_dot_protos_dot_blog__pb2.DeletePostLikeResponse.FromString,
                )


class BlogServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetPosts(self, request, context):
        """Post -------------------------------------------------------------------------------
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPostBySlug(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreatePost(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdatePostBySlug(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeletePostBySlug(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTags(self, request, context):
        """Tag --------------------------------------------------------------------------------
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTagBySlug(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPostComments(self, request, context):
        """Comment ----------------------------------------------------------------------------
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreatePostComment(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdatePostComment(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeletePostComment(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPostLikes(self, request, context):
        """Like -------------------------------------------------------------------------------
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreatePostLike(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeletePostLike(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_BlogServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetPosts': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPosts,
                    request_deserializer=blog_dot_protos_dot_blog__pb2.GetPostsRequest.FromString,
                    response_serializer=blog_dot_protos_dot_blog__pb2.GetPostsResponse.SerializeToString,
            ),
            'GetPostBySlug': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPostBySlug,
                    request_deserializer=blog_dot_protos_dot_blog__pb2.GetPostBySlugRequest.FromString,
                    response_serializer=blog_dot_protos_dot_blog__pb2.GetPostBySlugResponse.SerializeToString,
            ),
            'CreatePost': grpc.unary_unary_rpc_method_handler(
                    servicer.CreatePost,
                    request_deserializer=blog_dot_protos_dot_blog__pb2.CreatePostRequest.FromString,
                    response_serializer=blog_dot_protos_dot_blog__pb2.CreatePostResponse.SerializeToString,
            ),
            'UpdatePostBySlug': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdatePostBySlug,
                    request_deserializer=blog_dot_protos_dot_blog__pb2.UpdatePostBySlugRequest.FromString,
                    response_serializer=blog_dot_protos_dot_blog__pb2.UpdatePostBySlugResponse.SerializeToString,
            ),
            'DeletePostBySlug': grpc.unary_unary_rpc_method_handler(
                    servicer.DeletePostBySlug,
                    request_deserializer=blog_dot_protos_dot_blog__pb2.DeletePostBySlugRequest.FromString,
                    response_serializer=blog_dot_protos_dot_blog__pb2.DeletePostBySlugResponse.SerializeToString,
            ),
            'GetTags': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTags,
                    request_deserializer=blog_dot_protos_dot_blog__pb2.GetTagsRequest.FromString,
                    response_serializer=blog_dot_protos_dot_blog__pb2.GetTagsResponse.SerializeToString,
            ),
            'GetTagBySlug': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTagBySlug,
                    request_deserializer=blog_dot_protos_dot_blog__pb2.GetTagBySlugRequest.FromString,
                    response_serializer=blog_dot_protos_dot_blog__pb2.GetTagBySlugResponse.SerializeToString,
            ),
            'GetPostComments': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPostComments,
                    request_deserializer=blog_dot_protos_dot_blog__pb2.GetPostCommentsRequest.FromString,
                    response_serializer=blog_dot_protos_dot_blog__pb2.GetPostCommentsResponse.SerializeToString,
            ),
            'CreatePostComment': grpc.unary_unary_rpc_method_handler(
                    servicer.CreatePostComment,
                    request_deserializer=blog_dot_protos_dot_blog__pb2.CreatePostCommentRequest.FromString,
                    response_serializer=blog_dot_protos_dot_blog__pb2.CreatePostCommentResponse.SerializeToString,
            ),
            'UpdatePostComment': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdatePostComment,
                    request_deserializer=blog_dot_protos_dot_blog__pb2.UpdatePostCommentRequest.FromString,
                    response_serializer=blog_dot_protos_dot_blog__pb2.UpdatePostCommentResponse.SerializeToString,
            ),
            'DeletePostComment': grpc.unary_unary_rpc_method_handler(
                    servicer.DeletePostComment,
                    request_deserializer=blog_dot_protos_dot_blog__pb2.DeletePostCommentRequest.FromString,
                    response_serializer=blog_dot_protos_dot_blog__pb2.DeletePostCommentResponse.SerializeToString,
            ),
            'GetPostLikes': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPostLikes,
                    request_deserializer=blog_dot_protos_dot_blog__pb2.GetPostLikesRequest.FromString,
                    response_serializer=blog_dot_protos_dot_blog__pb2.GetPostLikesResponse.SerializeToString,
            ),
            'CreatePostLike': grpc.unary_unary_rpc_method_handler(
                    servicer.CreatePostLike,
                    request_deserializer=blog_dot_protos_dot_blog__pb2.CreatePostLikeRequest.FromString,
                    response_serializer=blog_dot_protos_dot_blog__pb2.CreatePostLikeResponse.SerializeToString,
            ),
            'DeletePostLike': grpc.unary_unary_rpc_method_handler(
                    servicer.DeletePostLike,
                    request_deserializer=blog_dot_protos_dot_blog__pb2.DeletePostLikeRequest.FromString,
                    response_serializer=blog_dot_protos_dot_blog__pb2.DeletePostLikeResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'blog.Blog', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Blog(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetPosts(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/blog.Blog/GetPosts',
            blog_dot_protos_dot_blog__pb2.GetPostsRequest.SerializeToString,
            blog_dot_protos_dot_blog__pb2.GetPostsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetPostBySlug(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/blog.Blog/GetPostBySlug',
            blog_dot_protos_dot_blog__pb2.GetPostBySlugRequest.SerializeToString,
            blog_dot_protos_dot_blog__pb2.GetPostBySlugResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CreatePost(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/blog.Blog/CreatePost',
            blog_dot_protos_dot_blog__pb2.CreatePostRequest.SerializeToString,
            blog_dot_protos_dot_blog__pb2.CreatePostResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def UpdatePostBySlug(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/blog.Blog/UpdatePostBySlug',
            blog_dot_protos_dot_blog__pb2.UpdatePostBySlugRequest.SerializeToString,
            blog_dot_protos_dot_blog__pb2.UpdatePostBySlugResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DeletePostBySlug(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/blog.Blog/DeletePostBySlug',
            blog_dot_protos_dot_blog__pb2.DeletePostBySlugRequest.SerializeToString,
            blog_dot_protos_dot_blog__pb2.DeletePostBySlugResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetTags(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/blog.Blog/GetTags',
            blog_dot_protos_dot_blog__pb2.GetTagsRequest.SerializeToString,
            blog_dot_protos_dot_blog__pb2.GetTagsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetTagBySlug(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/blog.Blog/GetTagBySlug',
            blog_dot_protos_dot_blog__pb2.GetTagBySlugRequest.SerializeToString,
            blog_dot_protos_dot_blog__pb2.GetTagBySlugResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetPostComments(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/blog.Blog/GetPostComments',
            blog_dot_protos_dot_blog__pb2.GetPostCommentsRequest.SerializeToString,
            blog_dot_protos_dot_blog__pb2.GetPostCommentsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CreatePostComment(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/blog.Blog/CreatePostComment',
            blog_dot_protos_dot_blog__pb2.CreatePostCommentRequest.SerializeToString,
            blog_dot_protos_dot_blog__pb2.CreatePostCommentResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def UpdatePostComment(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/blog.Blog/UpdatePostComment',
            blog_dot_protos_dot_blog__pb2.UpdatePostCommentRequest.SerializeToString,
            blog_dot_protos_dot_blog__pb2.UpdatePostCommentResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DeletePostComment(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/blog.Blog/DeletePostComment',
            blog_dot_protos_dot_blog__pb2.DeletePostCommentRequest.SerializeToString,
            blog_dot_protos_dot_blog__pb2.DeletePostCommentResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetPostLikes(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/blog.Blog/GetPostLikes',
            blog_dot_protos_dot_blog__pb2.GetPostLikesRequest.SerializeToString,
            blog_dot_protos_dot_blog__pb2.GetPostLikesResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CreatePostLike(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/blog.Blog/CreatePostLike',
            blog_dot_protos_dot_blog__pb2.CreatePostLikeRequest.SerializeToString,
            blog_dot_protos_dot_blog__pb2.CreatePostLikeResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DeletePostLike(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/blog.Blog/DeletePostLike',
            blog_dot_protos_dot_blog__pb2.DeletePostLikeRequest.SerializeToString,
            blog_dot_protos_dot_blog__pb2.DeletePostLikeResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
